# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/setup-gradle"
      - "/.github/actions/setup-java"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries: "*"
    labels: [ ]
    groups:
      kotlin-ksp:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.jvm"
          - "com.google.devtools.ksp"
      android-build-tools:
        patterns:
          - "com.android.tools.build:*"
          - "com.android.tools.lint:*"
    open-pull-requests-limit: 20
registries:
  maven-google:
    type: "maven-repository"
    url: "https://maven.google.com"
    replaces-base: true
