name: '📸 Paparazzi golden images'
description: 'Update Paparazzi golden images and commit the result'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  pr-number:
    description: 'PR number'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        token: ${{ inputs.github-token }}
    - if: inputs.pr-number != ''
      run: gh pr checkout "${{ inputs.pr-number }}"
      shell: bash
    - uses: ./.github/actions/check-git-lfs
    - uses: ./.github/actions/setup-java
    - uses: ./.github/actions/setup-gradle
    - uses: ./.github/actions/setup-gradle-properties
    - run: ./gradlew cleanRecordPaparazziRelease
      shell: bash
    - run: |
        git add -- '**/src/test/snapshots/**/*.png'

        if ! git diff --cached --quiet --exit-code -- '**/src/test/snapshots/**/*.png' ; then
          git config user.name 'spark-ui-bot'
          git config user.email 'spark-ui-bot@users.noreply.github.com'
          git commit -m "📸 Update Paparazzi golden images" -- '**/src/test/snapshots/**/*.png'
          git show

          if [[ -z "${INPUT_PR_NUMBER}" ]]; then
            new_pr_branch="paparazzi/$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER"
            git switch --create "$new_pr_branch"
            git push origin "$new_pr_branch"
            gh pr create \
              --title "chore: 📸 Update Paparazzi golden images" --fill \
              --base "$GITHUB_REF_NAME" --head "$new_pr_branch" \
              --assignee "$GITHUB_TRIGGERING_ACTOR"
          else
            git push
          fi
          echo "::notice::UPDATED"
        else
          echo "::notice::UP-TO-DATE"
        fi
      shell: bash
      env:
        INPUT_PR_NUMBER: ${{ inputs.pr-number }}
        GH_TOKEN: ${{ inputs.github-token }}
