name: '📸 Paparazzi golden images'
description: 'Update Paparazzi golden images and commit the result'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  pr-number:
    description: 'PR number'
    required: false
    type: number

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - if: ${{ inputs.pr-number }} != ''
      run: gh pr checkout "${{ inputs.pr-number }}"
      shell: bash
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: ./.github/actions/setup-gradle-properties
    - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
    - uses: actionsdesk/lfs-warning@e5f9a4c21f4bee104db7c0f23954dde59e5df909 # v3.2
    - uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c # v2.7.0
      with:
        arguments: recordPaparazziRelease
        gradle-home-cache-cleanup: true
    - run: |
        if ! git diff --quiet --exit-code -- **/src/test/snapshots/**/*.png ;
        then
          git config user.name 'spark-ui-bot'
          git config user.email 'spark-ui-bot@users.noreply.github.com'
          git commit **/src/test/snapshots/**/*.png -m "📸 Update Paparazzi golden images"
          git show
          git push
          echo "::notice::UPDATED"
        else
          echo "::notice::UP-TO-DATE"
        fi
      shell: bash
