name: '📦 Archive Paparazzi reports'
description: 'Archive Paparazzi reports and deltas'
runs:
  using: composite
  steps:
    - name: 'Archive report'
      uses: actions/upload-artifact@v4
      with:
        name: paparazzi-html
        path: '**/build/reports/paparazzi'
    - name: 'Archive deltas'
      if: ${{ hashFiles('**/build/paparazzi/failures/**.png') != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: paparazzi-delta
        path: '**/build/paparazzi/failures/**.png'
