name: '🐘 Setup Gradle'
description: 'Gradle setup and wrapper validation'
runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4.0.1
      with:
        validate-wrappers: true
        gradle-home-cache-cleanup: true
        add-job-summary-as-pr-comment: on-failure
