name: '🐘 Setup Gradle'
description: 'Gradle setup and wrapper validation'
runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@750cdda3edd6d51b7fdfc069d2e2818cf3c44f4c # v3.3.1
      with:
        validate-wrappers: true
        gradle-home-cache-cleanup: true
        add-job-summary-as-pr-comment: on-failure
