name: '🐘 Setup Gradle'
description: 'Gradle setup and wrapper validation'
runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
      with:
        validate-wrappers: true
        gradle-home-cache-cleanup: true
        add-job-summary-as-pr-comment: on-failure
