name: '🐘 Setup Gradle'
description: 'Gradle setup and wrapper validation'
runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4
      with:
        validate-wrappers: true
        gradle-home-cache-cleanup: true
        add-job-summary-as-pr-comment: on-failure
