name: '🐘 Setup Gradle'
description: 'Gradle setup and wrapper validation'
runs:
  using: composite
  steps:
    - uses: gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87 # v3.0.0
      with:
        gradle-home-cache-cleanup: true
    - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
