name: '🐘 Setup Gradle'
description: 'Gradle setup and wrapper validation'
runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
      with:
        validate-wrappers: true
        cache-cleanup: true
        add-job-summary-as-pr-comment: on-failure
