name: '💂 DependencyGuardBaseline'
description: 'Update dependencies baseline'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  pr-number:
    description: 'PR number'
    required: false
    type: number

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
    - if: ${{ inputs.pr-number }} != ''
      run: gh pr checkout "${{ inputs.pr-number }}"
      shell: bash
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: ./.github/actions/setup-gradle-properties
    - uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b # v1.0.6
    - uses: gradle/gradle-build-action@40b6781dcdec2762ad36556682ac74e31030cfe2 # v2.5.1
      with:
        arguments: dependencyGuardBaseline --no-configuration-cache
        gradle-home-cache-cleanup: true
    - run: |
        if ! git diff --quiet --exit-code -- **/dependencies/*.txt ;
        then
          git config user.name 'spark-ui-bot'
          git config user.email 'spark-ui-bot@users.noreply.github.com'
          git commit **/dependencies/*.txt -m "💂 Update dependencies baseline"
          git show
          git push
          echo "::notice::UPDATED"
        else
          echo "::notice::UP-TO-DATE"
        fi
      shell: bash
