name: '💂 DependencyGuardBaseline'
description: 'Update dependencies baseline'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  pr-number:
    description: 'PR number'
    required: false
    type: number

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.github-token }}
    - if: ${{ inputs.pr-number }} != ''
      run: gh pr checkout "${{ inputs.pr-number }}"
      shell: bash
    - uses: ./.github/actions/setup-java
    - uses: ./.github/actions/setup-gradle
    - uses: ./.github/actions/setup-gradle-properties
    - run: ./gradlew dependencyGuardBaseline --no-configuration-cache
      shell: bash
    - run: |
        if ! git diff --quiet --exit-code -- **/dependencies/*.txt ;
        then
          git config user.name 'spark-ui-bot'
          git config user.email 'spark-ui-bot@users.noreply.github.com'
          git commit **/dependencies/*.txt -m "💂 Update dependencies baseline"
          git show
          git push
          echo "::notice::UPDATED"
        else
          echo "::notice::UP-TO-DATE"
        fi
      shell: bash
