name: '📢 Diffuse AAR report'
description: 'Add diffuse AAR report to Pull Requests'
inputs:
  diffuse-version:
    description: 'Diffuse version'
    required: true
    default: '0.2.0'
runs:
  using: composite
  steps:
    - if: ${{ runner.os != 'linux' }}
      shell: bash
      run: |
        echo "Unsupported runner os ${{ runner.os }}"
        exit 1
    - uses: actions/cache@v4
      id: cache
      with:
        key: ${{ runner.os }}-diffuse-${{ inputs.diffuse-version }}-jar
        path: ~/.spark/diffuse-jar
    - name: 'Installing diffuse v${{ inputs.diffuse-version }}…'
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget "$DIFFUSE_URL" && chmod +x "$DIFFUSE_JAR"
        mkdir --parents ~/.spark/diffuse-jar && mv "$DIFFUSE_JAR" "$HOME/.spark/diffuse-jar/"
      env:
        DIFFUSE_URL: https://github.com/JakeWharton/diffuse/releases/download/${{ inputs.diffuse-version }}/diffuse-${{ inputs.diffuse-version }}-binary.jar
        DIFFUSE_JAR: diffuse-${{ inputs.diffuse-version }}-binary.jar
    - shell: bash
      run: |
        tee $GITHUB_STEP_SUMMARY << EOF || true
        <details><summary>📢 Diffuse reports…</summary>

        \`\`\`
        $(find . -path "*/build/outputs/aar/*-release.aar" -exec java -jar "$HOME/.spark/diffuse-jar/$DIFFUSE_JAR" info --aar {} \;)
        \`\`\`

        </details>
        EOF
      env:
        DIFFUSE_JAR: diffuse-${{ inputs.diffuse-version }}-binary.jar
