name: '📢 Diffuse AAR report'
description: 'Add diffuse AAR report to Pull Requests'
inputs:
  diffuse-version:
    description: 'Diffuse version'
    required: true
    default: '0.2.0'
runs:
  using: composite
  steps:
    - if: ${{ runner.os != 'linux' }}
      shell: bash
      run: |
        echo "Unsupported runner os ${{ runner.os }}"
        exit 1
    - uses: actions/cache@v4
      id: cache
      with:
        key: ${{ runner.os }}-diffuse-${{ inputs.diffuse-version }}-zip
        path: ~/.spark/diffuse
    - name: 'Installing diffuse v${{ inputs.diffuse-version }}…'
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget "$DIFFUSE_URL" && unzip "$DIFFUSE_ZIP" && rm "$DIFFUSE_ZIP"
        mkdir --parents ~/.spark/diffuse && mv "$DIFFUSE_DIR" "$HOME/.spark/diffuse/"
      env:
        DIFFUSE_URL: https://github.com/JakeWharton/diffuse/releases/download/${{ inputs.diffuse-version }}/diffuse-${{ inputs.diffuse-version }}.zip
        DIFFUSE_ZIP: diffuse-${{ inputs.diffuse-version }}.zip
        DIFFUSE_DIR: diffuse-${{ inputs.diffuse-version }}
    - shell: bash
      run: |
        tee $GITHUB_STEP_SUMMARY << EOF || true
        <details><summary>📢 Diffuse reports…</summary>

        \`\`\`
        $(find . -path "*/build/outputs/aar/*-release.aar" -exec "./$HOME/.spark/diffuse/$DIFFUSE_BIN" info --aar {} \;)
        \`\`\`

        </details>
        EOF
      env:
        DIFFUSE_BIN: diffuse-${{ inputs.diffuse-version }}/bin/diffuse
