name: 'Diffuse AAR'
description: 'Show diffuse AAR output'
inputs:
  pr-number:
    description: 'PR number'
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: wget "https://github.com/JakeWharton/diffuse/releases/download/0.1.0/diffuse-0.1.0-binary.jar"
    - shell: bash
      run: java -jar diffuse-0.1.0-binary.jar info --aar spark/build/outputs/aar/spark-release.aar | gh pr comment "$PR_NUMBER" --body-file -
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ inputs.pr-number }}