name: '🫵 Auto Author Assign'
on:
  pull_request:
    types: [ opened, reopened ]
jobs:
  assign-author:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@ebd30f10fb56e46eb0759a14951f36991426fed0 # v2.1.0
