name: '🫵 Auto Author Assign'
on:
  pull_request:
    types: [ opened, reopened ]
jobs:
  assign-author:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@293cfe93d5edcadd7354d954519f3bb441d9d695 # v2.0.0
