name: '🫵 Auto Author Assign'
on:
  pull_request:
    types: [ opened, reopened ]
jobs:
  assign-author:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@c1ffd6f64e20f8f5f61f4620a1e5f0b0908790ef # v2.0.1
