name: '🫵 Auto Author Assign'
on:
  pull_request:
    types: [ opened, reopened ]
permissions:
  pull-requests: write
jobs:
  assign-author:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@16f0022cf3d7970c106d8d1105f75a1165edb516 # v2.1.1
