name: '♻️ Clear GitHub Actions cache'
on:
  workflow_dispatch:
  pull_request:
#    types: [ closed ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh extension install actions/gh-actions-cache
      - run: gh actions-cache list
