name: '📸 Paparazzi Golden Images'

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force rendering of all golden images'
        required: true
        default: false
        type: boolean

jobs:
  paparazzi-golden-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/paparazzi-golden-images
        with:
          github-token: ${{ secrets.PAT_SPARK || secrets.GITHUB_TOKEN }}
          force: ${{ inputs.force }}
