name: '📸 Paparazzi Golden Images'

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'PR number, branch, or url'
        required: false
        type: string

jobs:
  paparazzi-golden-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/paparazzi-golden-images
        with:
          github-token: ${{ secrets.PAT_SPARK || secrets.GITHUB_TOKEN }}
          pr-number: ${{ inputs.ref }}
