name: '🎨 PR icon updates'

on:
  push:
    branches: [ "chore-updated-icons" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  pr-icon-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: chore-updated-icons
          fetch-depth: 0
      - run: gh pr create --fill
        continue-on-error: true
